# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Projects/Basys-3-Master.xdc

# IP: C:/Users/niels/Documents/Bachelor IoT 23-24/23-24 Digital sytem development/project/fpga-projects-master/DontHitTheBars/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
